version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
  api:
    container_name: api
    image: rumm-api-auth:alplha
    build: .
    env_file: .env.container
    ports:
      - '80:80'
    depends_on:
      - database
    restart: unless-stopped
  database:
    container_name: database
    restart: unless-stopped
    image: kartoza/postgis:13-3.1
    env_file: .env.container
    environment:
      POSTGRES_DBNAME: "${RUMM_DBNAME}"
      POSTGRES_USER: "${RUMM_DBUSER}"
      POSTGRES_PASS: "${RUMM_DBPASS}"
      POSTGRES_PASSWORD: "${RUMM_DBPASS}"
      POSTGRES_DB: "${RUMM_DBNAME}"
    volumes:
      - pg_database:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '25432:5432'
  redis:
    container_name: redis
    image: redis:alpine3.13
    restart: unless-stopped
    volumes:
      - redisdata:/data
volumes:
  portainer:
  pg_database:
  redisdata: