version: '3'
services:
  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
  api:
    container_name: api
    image: rumm-api-auth:alplha
    build: .
    env_file:
      - ./.env.container
    ports:
      - '8001:8001'
    depends_on:
      - database
    restart: unless-stopped
  database:
    container_name: database
    restart: unless-stopped
    image: postgis/postgis:13-master
    env_file:
      - ./.env.container
    environment:
      POSTGRES_USER: ${AUTH_API_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_API_DB_PASS}
      POSTGRES_DB: ${AUTH_API_DB_NAME}
    volumes:
      - pg_database:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    container_name: redis
    image: redis:alpine3.13
    restart: unless-stopped
    volumes:
      - redisdata:/data
volumes:
  portainer:
  pg_database:
  redisdata:
